import turtle
turtle.colormode(255)
turtle.bgcolor('white')
yang = turtle.Turtle()
ying = turtle.Turtle()
turtle.tracer(0)
yang.speed(0)
ying.speed(0)
for times in range (360):
    ying.color(0, 0, 0)
    ying.begin_fill()
    ying.circle(152)
    ying.end_fill()
    ying.left(1)
for times in range (180):
    ying.color(0, 0, 0)
    ying.begin_fill()
    ying.circle(150)
    ying.left(181)
    ying.end_fill()
for times in range (180):
    yang.color(255, 255, 255)
    yang.begin_fill()
    yang.circle(150)
    yang.left(1)
    yang.end_fill()
for times in range (2):
    ying.color(0, 0, 0)
    ying.begin_fill()
    ying.circle(150)
    ying.left(1)
    ying.end_fill()
for times in range (1):
    yang.penup()
    yang.right(115)
    yang.forward(140)
    yang.pendown()
    yang.begin_fill()
    yang.color(0, 0, 0)
    yang.circle(50)
    yang.end_fill()
for times in range (1):
    yang.penup()
    yang.right(179)
    yang.forward(280)
    yang.pendown()
    yang.begin_fill()
    yang.color(255, 255, 255)
    yang.circle(50)
    yang.end_fill()
